sonar.organization=somethingwithproof
sonar.host.url=https://sonarcloud.io
sonar.sources=roles,.github,galaxy.yml
sonar.tests=molecule
sonar.test.inclusions=molecule/**/*.yml
sonar.exclusions=**/.ansible/**,**/.cache/**,**/.molecule/**,**/__pycache__/**,.omc/**,.worktrees/**
