---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:
    - name: Include policy role
      ansible.builtin.include_role:
        name: thomasvincent.firewall.policy

    - name: Include nftables role
      ansible.builtin.include_role:
        name: thomasvincent.firewall.nftables
